version: '3.1'

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ada-teste
      MARIADB_DATABASE: ada-db
  # back:
  #   build: ./BACK
  #   links:
  #     - "db:database"
  #   ports:
  #     - "5000:5000"
  front:
    build: ./FRONT
    ports:
      - "3000:3000"

volumes:
  db_data: